# -*- coding: utf-8 -*-
"""model_trainyolo10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuAgoJaiijz5fB6h1xOhhRusYrtlB_Ab
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/data

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10

!pip install .

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

# Commented out IPython magic to ensure Python compatibility.
dir_path = "/content/drive/MyDrive/data/yolov10"
# %cd {dir_path}

!yolo detect train \
data={dir_path}/custom_dataset.yaml\
model={dir_path}/yolov10n.pt \
epochs=50 batch=8

# Commented out IPython magic to ensure Python compatibility.
dir_path = "/content/drive/MyDrive/data/yolov10"
# %cd {dir_path}

!yolo predict \
model={dir_path}/runs/detect/train/weights/best.pt \
source={dir_path}/test/images/01.jpeg